/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ConfiguracionRouteImport } from './routes/configuracion'
import { Route as FacturasRouteImport } from './routes/facturas'
import { Route as NuevaRouteImport } from './routes/nueva'
import { Route as FacturasIndexRouteImport } from './routes/facturas.index'
import { Route as FacturasIdRouteImport } from './routes/facturas.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracionRoute = ConfiguracionRouteImport.update({
  id: '/configuracion',
  path: '/configuracion',
  getParentRoute: () => rootRouteImport,
} as any)
const FacturasRoute = FacturasRouteImport.update({
  id: '/facturas',
  path: '/facturas',
  getParentRoute: () => rootRouteImport,
} as any)
const NuevaRoute = NuevaRouteImport.update({
  id: '/nueva',
  path: '/nueva',
  getParentRoute: () => rootRouteImport,
} as any)
const FacturasIndexRoute = FacturasIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FacturasRoute,
} as any)
const FacturasIdRoute = FacturasIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => FacturasRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/configuracion': typeof ConfiguracionRoute
  '/facturas': typeof FacturasRouteWithChildren
  '/nueva': typeof NuevaRoute
  '/facturas/$id': typeof FacturasIdRoute
  '/facturas/': typeof FacturasIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/configuracion': typeof ConfiguracionRoute
  '/nueva': typeof NuevaRoute
  '/facturas/$id': typeof FacturasIdRoute
  '/facturas': typeof FacturasIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/configuracion': typeof ConfiguracionRoute
  '/facturas': typeof FacturasRouteWithChildren
  '/nueva': typeof NuevaRoute
  '/facturas/$id': typeof FacturasIdRoute
  '/facturas/': typeof FacturasIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/configuracion'
    | '/facturas'
    | '/nueva'
    | '/facturas/$id'
    | '/facturas/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/configuracion' | '/nueva' | '/facturas/$id' | '/facturas'
  id:
    | '__root__'
    | '/'
    | '/configuracion'
    | '/facturas'
    | '/nueva'
    | '/facturas/$id'
    | '/facturas/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConfiguracionRoute: typeof ConfiguracionRoute
  FacturasRoute: typeof FacturasRouteWithChildren
  NuevaRoute: typeof NuevaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracion': {
      id: '/configuracion'
      path: '/configuracion'
      fullPath: '/configuracion'
      preLoaderRoute: typeof ConfiguracionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/facturas': {
      id: '/facturas'
      path: '/facturas'
      fullPath: '/facturas'
      preLoaderRoute: typeof FacturasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nueva': {
      id: '/nueva'
      path: '/nueva'
      fullPath: '/nueva'
      preLoaderRoute: typeof NuevaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/facturas/': {
      id: '/facturas/'
      path: '/'
      fullPath: '/facturas/'
      preLoaderRoute: typeof FacturasIndexRouteImport
      parentRoute: typeof FacturasRoute
    }
    '/facturas/$id': {
      id: '/facturas/$id'
      path: '/$id'
      fullPath: '/facturas/$id'
      preLoaderRoute: typeof FacturasIdRouteImport
      parentRoute: typeof FacturasRoute
    }
  }
}

interface FacturasRouteChildren {
  FacturasIdRoute: typeof FacturasIdRoute
  FacturasIndexRoute: typeof FacturasIndexRoute
}

const FacturasRouteChildren: FacturasRouteChildren = {
  FacturasIdRoute: FacturasIdRoute,
  FacturasIndexRoute: FacturasIndexRoute,
}

const FacturasRouteWithChildren = FacturasRoute._addFileChildren(
  FacturasRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConfiguracionRoute: ConfiguracionRoute,
  FacturasRoute: FacturasRouteWithChildren,
  NuevaRoute: NuevaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
