/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ConfiguracionRouteImport } from './routes/configuracion'
import { Route as FacturasRouteImport } from './routes/facturas'
import { Route as HoyRouteImport } from './routes/hoy'
import { Route as LoginRouteImport } from './routes/login'
import { Route as NuevaRouteImport } from './routes/nueva'
import { Route as FacturasIndexRouteImport } from './routes/facturas.index'
import { Route as FacturasIdRouteImport } from './routes/facturas.$id'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracionRoute = ConfiguracionRouteImport.update({
  id: '/configuracion',
  path: '/configuracion',
  getParentRoute: () => rootRouteImport,
} as any)
const FacturasRoute = FacturasRouteImport.update({
  id: '/facturas',
  path: '/facturas',
  getParentRoute: () => rootRouteImport,
} as any)
const HoyRoute = HoyRouteImport.update({
  id: '/hoy',
  path: '/hoy',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const NuevaRoute = NuevaRouteImport.update({
  id: '/nueva',
  path: '/nueva',
  getParentRoute: () => rootRouteImport,
} as any)
const FacturasIndexRoute = FacturasIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FacturasRoute,
} as any)
const FacturasIdRoute = FacturasIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => FacturasRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/configuracion': typeof ConfiguracionRoute
  '/facturas': typeof FacturasRouteWithChildren
  '/hoy': typeof HoyRoute
  '/login': typeof LoginRoute
  '/nueva': typeof NuevaRoute
  '/facturas/$id': typeof FacturasIdRoute
  '/facturas/': typeof FacturasIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/configuracion': typeof ConfiguracionRoute
  '/hoy': typeof HoyRoute
  '/login': typeof LoginRoute
  '/nueva': typeof NuevaRoute
  '/facturas/$id': typeof FacturasIdRoute
  '/facturas': typeof FacturasIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/configuracion': typeof ConfiguracionRoute
  '/facturas': typeof FacturasRouteWithChildren
  '/hoy': typeof HoyRoute
  '/login': typeof LoginRoute
  '/nueva': typeof NuevaRoute
  '/facturas/$id': typeof FacturasIdRoute
  '/facturas/': typeof FacturasIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/configuracion'
    | '/facturas'
    | '/hoy'
    | '/login'
    | '/nueva'
    | '/facturas/$id'
    | '/facturas/'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/configuracion'
    | '/hoy'
    | '/login'
    | '/nueva'
    | '/facturas/$id'
    | '/facturas'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/configuracion'
    | '/facturas'
    | '/hoy'
    | '/login'
    | '/nueva'
    | '/facturas/$id'
    | '/facturas/'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConfiguracionRoute: typeof ConfiguracionRoute
  FacturasRoute: typeof FacturasRouteWithChildren
  HoyRoute: typeof HoyRoute
  LoginRoute: typeof LoginRoute
  NuevaRoute: typeof NuevaRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracion': {
      id: '/configuracion'
      path: '/configuracion'
      fullPath: '/configuracion'
      preLoaderRoute: typeof ConfiguracionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/facturas': {
      id: '/facturas'
      path: '/facturas'
      fullPath: '/facturas'
      preLoaderRoute: typeof FacturasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hoy': {
      id: '/hoy'
      path: '/hoy'
      fullPath: '/hoy'
      preLoaderRoute: typeof HoyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nueva': {
      id: '/nueva'
      path: '/nueva'
      fullPath: '/nueva'
      preLoaderRoute: typeof NuevaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/facturas/': {
      id: '/facturas/'
      path: '/'
      fullPath: '/facturas/'
      preLoaderRoute: typeof FacturasIndexRouteImport
      parentRoute: typeof FacturasRoute
    }
    '/facturas/$id': {
      id: '/facturas/$id'
      path: '/$id'
      fullPath: '/facturas/$id'
      preLoaderRoute: typeof FacturasIdRouteImport
      parentRoute: typeof FacturasRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface FacturasRouteChildren {
  FacturasIdRoute: typeof FacturasIdRoute
  FacturasIndexRoute: typeof FacturasIndexRoute
}

const FacturasRouteChildren: FacturasRouteChildren = {
  FacturasIdRoute: FacturasIdRoute,
  FacturasIndexRoute: FacturasIndexRoute,
}

const FacturasRouteWithChildren = FacturasRoute._addFileChildren(
  FacturasRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConfiguracionRoute: ConfiguracionRoute,
  FacturasRoute: FacturasRouteWithChildren,
  HoyRoute: HoyRoute,
  LoginRoute: LoginRoute,
  NuevaRoute: NuevaRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
